task/DES-1828 Streetview
TACC-Cloud/geoapi pull request #46
Opened 2021-03-16 18:51 UTC by duckonomy

## Overview: ##

## PR Status: ##

* [ ] Ready.
* [X] Work in Progress.
* [ ] Hold.

## Related Jira tickets: ##

* [DES-1839](https://jira.tacc.utexas.edu/browse/DES-1839)
* [DES-1828](https://jira.tacc.utexas.edu/browse/DES-1828)
* [DES-1893](https://jira.tacc.utexas.edu/browse/DES-1893)

## Summary of Changes: ##
* [x] Separate panel for Streetview
  * [x] Icon?
  * [x] Tabs for Accounts, Upload Log, and Uploaded assets (streamed from Streetview service)
* [x] Upload Log
  * [X] Separate status indicators for notification types 
  * [X] Progress bar
* [x] Accounts tab for indicating authorization status
  * [x] Auth routing 
* [ ] Assets
  * [x] Get mapillary sequence data from geoapi
  * [x] Notify user of pending approval
  * [ ] Implement changesets for mapillary 
* [x] Streetview publishing modal
  * [x] Select service (maybe checkbox?
* [ ] Display sequence features in the map
  * [x] Make each feature a marker layer 
  * [x] Open link to streetview on clicking point (with image key)
  * [x] Get thumbs from mapillary    
  * [ ] Lon/lat based mapillary open

## Testing Steps: ##

## Notes: ##

2021-04-22 16:02 UTC, nathanfranklin requested changes
Awesome work.  Very cool to see and I know it was a huge challenge to interconnect tapis/geoapi/mapillary!  Well done! 💯 🥇 




I'm still testing the related frontend PR but wanted to give some feedback here first.  I left some comments on the code and below are some additional thing to consider:


* run flake8 on some of the files.  long term, we should set that up in our CI pipeline but in the short term we should just run it locally and try to fix any linting erros on new code.
* consider adding some additional context to logger statements to aid in searching splunk logs.  Like maybe info on the action and who was doing it with some parameters: logger.error("Errors during mapillary upload for user: {} system:{} path:{}"...

I like the progress related notifications.
  * maybe, we can figure out how to connect that to Task somehow as that is used in a similar situation with point cloud processing.  (follow on ticket?) . both are about finding info about long-running tasks (and supporting canceling etc).
  * is there anyway that notifications routes could be combined? or does that not make sense. I haven't thought this through. :) but just wondering though as it would be nice to just pull one thing).  [Don't consider this too long; The above point about use with Task is what I'm most curious about]

2021-05-13 21:36 UTC, duckonomy commented on geoapi/utils/streetview.py
> +        subprocess.run(command,
Added check with try/catch.

2021-05-13 21:37 UTC, duckonomy commented on geoapi/routes/projects.py
> +@api.route('/<int:projectId>/users/<username>/streetview/<service>')
Created a separate route file for streetviews

2021-05-13 21:44 UTC, duckonomy commented on geoapi/tasks/streetview.py
> +        NotificationsService.create(user, "success", "Cleaning up previous session before upload.")
- I've added removes for errors for now
- For now, it doesn't proceed and throw a warning if there is an existing task or directory (in `from_tapis_to_streetview`).

2021-05-13 21:45 UTC, duckonomy commented on geoapi/routes/notifications.py
> +    def delete(self):
I've changed the frontend to indicate that we're only removing the logs. I will have a separate PR for actual abort.

2022-04-20 15:57 UTC, nathanfranklin reviewed
I'm still working through this but wanted to leave some comments

2022-04-20 15:57 UTC, nathanfranklin commented on geoapi/routes/streetview.py
> +    def delete(self, streetview_id: int):
we should look at ensuring that users can only delete their own items in these routes.  Same would apply, for the GETs.

2022-04-21 19:10 UTC, nathanfranklin commented on geoapi/tasks/streetview.py
> +                                                message="Transferring files from DesignSafe to geoapi",
Should this be more generic?  "Collecting files"

2022-04-21 19:11 UTC, nathanfranklin commented on geoapi/tasks/streetview.py
> +                                            "Started upload to Mapillary")
```suggestion
                                            "Uploading to Mapillary")
```

suggestion is to have the same form as the previous notification

2022-04-25 19:33 UTC, nathanfranklin commented on geoapi/routes/projects.py
> +})
drop?

2022-04-25 19:35 UTC, nathanfranklin commented on geoapi/routes/projects.py
> +})
```suggestion
```

drop?  defined earlier.

2022-04-25 20:47 UTC, nathanfranklin commented on geoapi/services/notifications.py
> +
```suggestion
```
duplicates of `getProgress` and `getProgressUID` which are the ones used.

2022-04-25 21:45 UTC, nathanfranklin commented on geoapi/routes/streetview.py
> +    def delete(self, streetview_id: int):
We have a ticket for this so resolving

2022-04-26 20:36 UTC, duckonomy commented on geoapi/tasks/streetview.py
> +def upload(user: User, params: Dict):
I left it here because `task/streetview.py` imports the service file (thus circular dependency).

2022-04-26 21:16 UTC, nathanfranklin commented on geoapi/tasks/streetview.py
> +def upload(user: User, params: Dict):
gotcha 👍

2022-04-26 21:35 UTC, nathanfranklin commented on geoapi/tasks/streetview.py
> +                                                message="Collecting files from DesignSafe to geoapi",
Could we drop "geoapi".  Either "Collection files" or "Collecting files from DesignSafe"

2022-04-27 14:27 UTC, nathanfranklin commented on Dockerfile
> +RUN pip install --upgrade git+https://github.com/mapillary/mapillary_tools
adding a note in the[ ticket for updating packages (and using poetry)](https://jira.tacc.utexas.edu/browse/DES-2213) to pin this to a version or commit.

2022-04-27 15:41 UTC, merged