Implement uploading <project_uuid>.hazmapper to tapis.
TACC-Cloud/geoapi pull request #54
Opened 2021-04-08 22:59 UTC by duckonomy

## Overview: ##
Implement saving the project file to tapis.

## PR Status: ##

* [X] Ready.
* [ ] Work in Progress.
* [ ] Hold.

## Related Jira tickets: ##

* [DES-1929](https://jira.tacc.utexas.edu/browse/DES-1929)

## Summary of Changes: ##
Adds necessary route/service for the upload process and a new tapis interaction in `agave.py`

## Testing Steps: ##
1. Test with the HazMapper GUI

## Notes: ##
I wasn't sure how to test the Tapis part. I've tried creating a mock like the `agave_utils_with_geojson_file_mock` but wasn't sure if that could update on making the call.

2021-04-27 14:45 UTC, reptillicus commented
It looks like there should also be a migration in here too? The additional fields in the project model  will need one.

2021-05-19 14:00 UTC, nathanfranklin approved these changes
LGTM 👍 

Just note two follow on things:
* comment about logging
* potentially deriving 'system_name' on the front end instead of having in model

2021-05-25 02:44 UTC, nathanfranklin requested changes
Just left one comment to consider and also for 3038e1d74ecc7ed722e3d232b311651b726a81fc, is there a migration that goes along with it (as we have an early commit of this branch deployed on staging). 👍

2021-05-25 02:44 UTC, nathanfranklin commented on geoapi/routes/public_projects.py
> +@api.route('/<int:projectId>/export/')
I don't think we need this as we don't want to offer this route to unauthenticated users, right?

2021-05-28 22:25 UTC, nathanfranklin approved these changes
Awesome 💯

2021-06-04 20:37 UTC, merged